
[//]: # (DO NOT EDIT. index.md is generated by nbpages. Make changes to templates/index.md.tpl.)

# ND Pyomo Cookbook

**ND Pyomo Cookbook** is a collection of notebooks showing how to use [Pyomo](http://www.pyomo.org/) to solve
modeling and optimization problems. With Pyomo, one can embed within Python an optimization model consisting of
**decision variables**, **constraints**, and an optimization **objective**. A rich set of features enables the modeling
and analysis of complex systems.

The notebooks in this collection were developed for instructional purposes at Notre Dame. Originally
developed using the [Anaconda distribution of Python](https://www.anaconda.com/download/), the notebooks have been
updated to open directly [Google Colaboratory](https://colab.research.google.com/) where they can be run using
only a browser window.

PyomoFest at Notre Dame was held June 5-7, 2018. This repository contains the
[agenda](https://github.com/jckantor/ND-Pyomo-Cookbook/tree/master/PyomoFest/PyomoFest.md),
[slides](https://github.com/jckantor/ND-Pyomo-Cookbook/tree/master/PyomoFest/slides) and
[exercises](https://github.com/jckantor/ND-Pyomo-Cookbook/tree/master/PyomoFest/exercises_wo_soln/exercises)
distributed during that event.

{% for line in readme_toc -%}
{{ line }}
{% endfor %}
